# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 835908b16918853dc56034281c2d3568bdec29e25c9e6ec9887e442b53a84a1d15a3b7bfb6cb77b5fb9f2aa196e6037ccf8e9f5e9182b504a24c9d89010f1268

test:
  secret_key_base: 4ecae844f2945eff60e954bb8930181ec61cc4976088d7b736add23a959638a12858c8495a7c9264c3635796fbb51704bf31cfd7026c40f2dbd8f2019d6e99e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
